# Generated by Django 5.1.6 on 2025-02-24 21:43

from django.db import migrations

def migrar_dados(apps, schema_editor):
    """
    Função personalizada para migrar dados.
    """
    # Obtém os modelos antigos e novos usando o `apps` do Django
    UserLogin = apps.get_model('reservyApp', 'UserLogin')
    Usuario = apps.get_model('reservyApp', 'Usuario')

    # Exemplo: Migrar todos os usuários do UserLogin para o modelo Usuario
    for user_login in UserLogin.objects.all():
        Usuario.objects.create(
            nome=user_login.email.split('@')[0],  # Exemplo: usar o nome do email
            siape='000000',  # Defina um valor padrão para o SIAPE
            email=user_login.email,
            cpf='00000000000',  # Defina um valor padrão para o CPF
            senha=user_login.password,  # Migra a senha hash
            telefone='00000000000'  # Defina um valor padrão para o telefone
        )

class Migration(migrations.Migration):
    dependencies = [
        ('reservyApp', '0001_initial'),  # Depende da migração inicial
    ]

    operations = [
        migrations.RunPython(migrar_dados),  # Adiciona a operação personalizada
    ]