# Generated by Django 5.1.6 on 2025-02-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservyApp', '0002_reservyApp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrevia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('siape', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('negado', 'Negado')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservyApp.usuario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('espaco', 'Espaço'), ('veiculo', 'Veículo')], max_length=10),
        ),
    ]
